name: Run Tests on Pull Request
run-name: ìƒˆë¡œìš´ PR ìƒì„±ë˜ì–´, í…ŒìŠ¤íŠ¸ë¥¼ ì§„í–‰í•©ë‹ˆë‹¤ ğŸ§ª
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      # GitHub ë¦¬í¬ì§€í† ë¦¬ ì½”ë“œ ì²´í¬ì•„ì›ƒ
      - name: Check out repository code
        uses: actions/checkout@v4

      # Node.js ì„¤ì •
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Node.js ë²„ì „ì„ í•„ìš”ì— ë§ê²Œ ì§€ì •

      # ì˜ì¡´ì„± ì„¤ì¹˜
      - name: Install dependencies
        run: npm install

      # í…ŒìŠ¤íŠ¸ ì‹¤í–‰
      - name: Run tests
        run: npm run test

      # ì™„ë£Œ
      - run: echo "ğŸ ì‹¤í–‰ ì™„ë£Œ! ${{ job.status }}."
